### ISSUE TITLE
pyflakes报'arguments' object has no attribute 'kwonlyargs'错误，求助

### ISSUE THREAD

**Issue by netxfly** [wklken/k-vim#204]
"run.py" [noeol] 45L, 1212C
处理 function <SNR>160_RunPyflakes 时发生错误:
第   50 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 84, in check
  File "/home/hartnett/k-vim-9.0/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 253, in __init__
    self.handleChildren(tree)
  File "/home/hartnett/k-vim-9.0/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 520, in handleChildren
    self.handleNode(node, tree)
  File "/home/hartnett/k-vim-9.0/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 555, in handleNode
    handler(node)
  File "/home/hartnett/k-vim-9.0/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 702, in FUNCTIONDEF
    self.LAMBDA(node)
  File "/home/hartnett/k-vim-9.0/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 722, in LAMBDA
    for arg in node.args.args + node.args.kwonlyargs:
AttributeError: 'arguments' object has no attribute 'kwonlyargs'
请按 ENTER 或其它命令继续

**Comment by wklken** [comment]
确认下
1. python版本
2. pyflakes的版本

**Comment by netxfly** [comment]
$ python -V                                                                        
Python 2.7.11
$ cat ~/k-vim-9.0/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/__init__.py

__version__ = '0.7.3'

**Comment by netxfly** [comment]
pyflakes已经到1.1.0后不报错了，我先试用下

**Comment by wklken** [comment]
应该是版本问题, pyflakes官方有这个bug, 2014年已经修复....

**Comment by alyato** [comment]
@netxfly @wklken  pylakes 版本是1.5.0，但是还是出现这种情况
