### ISSUE TITLE
[建议]: 设置YouCompleteMe的g:ycm_server_python_interpreter变量

### ISSUE THREAD

**Issue by bwangel23** [wklken/k-vim#223]
我的ycm是在Python2下编译的，系统默认的python解释器也是Python2，但是自己设置了一个虚拟环境，默认的python解释器是Python3，于是打开一个Python文件的时候报出如下错误：

```
The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Run ':YcmToggleLogs stderr' to check the logs.
```

我输入了`:YcmToggleLogs`后显示的错误日志如下：

```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/michael/Bundle/k-vim/bundle/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 183, in <module>
    Main()
  File "/home/michael/Bundle/k-vim/bundle/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 158, in Main
    extra_conf_store.CallGlobalExtraConfYcmCorePreloadIfExists()
  File "/home/michael/Bundle/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py", line 73, in CallGlobalExtraConfYcmCorePreloadIfExists
    _CallGlobalExtraConfMethod( 'YcmCorePreload' )
  File "/home/michael/Bundle/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py", line 91, in _CallGlobalExtraConfMethod
    module = Load( global_ycm_extra_conf, force = True )
  File "/home/michael/Bundle/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py", line 149, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "/home/michael/Bundle/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/utils.py", line 329, in LoadPythonSource
    return importlib.machinery.SourceFileLoader( name, pathname ).load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/michael/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py", line 32, in <module>
    import ycm_core
ImportError: dynamic module does not define init function (PyInit_ycm_core)
```

后来我在ycm的readme中看到了这个FAQ: [I get ImportError exceptions that mention PyInit_ycm_core or initycm_core](https://github.com/Valloric/YouCompleteMe#i-get-importerror-exceptions-that-mention-pyinit_ycm_core-or-initycm_core)，发现出错原因就是python解释器设置错了！

因此建议设置`g:ycm_server_python_interpreter`，为`/usr/bin/python`！

关于这个设置，我是这样想的！在k-vim的安装脚本中，执行的安装命令是`python install.py --clang-completer --system-libclang `，这样的话，如果没有在virtualenv中安装k-vim，默认的选择的Python解释器都是`/usr/bin/python`吧，应该没有人会在virtualenv中安装k-vim吧！
`

**Comment by bwangel23** [comment]
刚刚想到了一种更好的解决办法，在k-vim安装脚本中添加如下语句

```
PYTHON=`which python`
sed -i "/let g:ycm_seed.*1$/a\ \ \ \ \"\ 设置Python解释器的路径\n\ \ \ \ let g:ycm_server_python_interpreter = '$PYTHON'" ./vimrc.bundles
```

上面命令的运行结果如下:
```
diff --git a/vimrc.bundles b/vimrc.bundles
index d7ac2d7..e811c66 100644
--- a/vimrc.bundles
+++ b/vimrc.bundles
@@ -367,6 +367,8 @@ call plug#end()
     let g:ycm_collect_identifiers_from_tags_files = 1
     " 开启语法关键字补全
     let g:ycm_seed_identifiers_with_syntax=1
+    " 设置Python解释器的路径
+    let g:ycm_server_python_interpreter = '/usr/bin/python'
 
     "let g:ycm_seed_identifiers_with_syntax=1   "语言关键字补全, 不过python关键字都很短，所以，需要的自己打开
```

**Comment by bwangel23** [comment]
算了，我直接提交一个pr过来吧!

**Comment by wklken** [comment]
`sed -i` 在mac下不能用, 

https://github.com/Valloric/YouCompleteMe#the-gycm_server_python_interpreter-option

遇到这个问题的人, 自取解决, 自行加一行配置就是了, 但是并不提供统一的解法, 因为大多数人并不需要, 会使配置复杂化

---------

thx:)

**Comment by bwangel23** [comment]
好吧，用的Ubuntu，一时忘了Mac了！

**Comment by linghutf** [comment]
Ubuntu16.04依然不起作用

**Comment by bwangel23** [comment]
@linghutf ，你报的错误是什么，能贴上来看看吗？

**Comment by linghutf** [comment]
@bwangel23 已经解决了，禁用`vim-textobj-entire`就可以了。

**Comment by wklken** [comment]
`vim-textobj-entire`文本对象选择, 会导致什么错误呢? @linghutf

**Comment by yech1990** [comment]
为什么我没有这个变量可以设置

Ubuntu 16.04

**Comment by linghutf** [comment]
@wklken 这个插件会导致Unicode编码错误,详见[#2136](https://github.com/Valloric/YouCompleteMe/issues/2136)

**Comment by 929440925** [comment]
Centos7的要如何搞呢

**Comment by ALENGTH** [comment]
好吧，我得说一句，这玩意儿真的苟，当你用arch的时候，最好的方法就是挨着试，arch上python有好几个，python python2 python3 python3.7 python3.7m。。。。。我只能说挨着试一下总是没错的

**Comment by wklken** [comment]
just add and use, 会自动识别使用的python, 包括virtualenv中的

```
let g:ycm_python_binary_path = 'python'
```
